name: Install system dependencies
description: Install apt packages with index refresh and retries
inputs:
  packages:
    description: Space-delimited apt package names
    required: true
runs:
  using: composite
  steps:
    - name: Install apt dependencies
      shell: bash
      run: |
        sudo apt-get -o Acquire::Retries=3 update
        sudo apt-get -o Acquire::Retries=3 install -y --no-install-recommends ${{ inputs.packages }}
